name: test

# On every pull request, but only on push to master
on:
  push:
    branches:
    - master
  pull_request:

permissions:
  contents: read

jobs:
  test-node:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: volta-cli/action@2d68418f32546fd191eb666e232b321d5726484d # v4.1.1
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn
          yarn bootstrap

      - name: Run tests
        run: |
          yarn lint  
          yarn test ci

      - name: Coveralls
        uses: coverallsapp/github-action@09b709cf6a16e30b0808ba050c7a6e8a5ef13f8d # v1.2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
