name: test

# On every pull request, but only on push to master
on:
  push:
    branches:
    - master
  pull_request:

permissions:
  contents: read

jobs:
  test-node:
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: read

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Use Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn bootstrap

      - name: Run tests
        run: yarn test-ci

      - name: Coveralls
        uses: coverallsapp/github-action@09b709cf6a16e30b0808ba050c7a6e8a5ef13f8d # v1.2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
