name: test

# On every pull request, but only on push to master
on:
  push:
    branches:
    - master
  pull_request:

permissions:
  contents: read

jobs:
  test-node:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    permissions:
      checks: write
      contents: read

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: volta-cli/action@2d68418f32546fd191eb666e232b321d5726484d # v4.1.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false 

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test-ci

      - name: Coveralls
        uses: coverallsapp/github-action@09b709cf6a16e30b0808ba050c7a6e8a5ef13f8d # v1.2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
